### PR TITLE
[Fixes #12] provide both a walk-sync compatible API + use walkSync un…

### LINKED ISSUE #12: Globs in readSync should behave the same as walk-sync
The glob options in readSync behaved unexpectedly and I worked around it by creating the pojo from walk-sync, when I get around to it, I'll submit a PR here to do the same thing.

https://github.com/broccolijs/broccoli-test-helper/blob/master/src/util.ts#L29

### PR DESCRIPTION
**Pull request by stefanpenner**
…der the hood

* deprecates options.include in-favor of walk-sync’s options.glob
* deprecates options.exclude in-favor of walk-sync’s options.ignore

- [x] test deprecation code
- [x]  @krisselden review

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -28,55 +29,47 @@ namespace fixturify {
...
-
-    let includeMatcher;
-    let excludeMatcher;
-
-    if (include) {
-      includeMatcher = new MatcherCollection(include);
-    }
-    if (exclude) {
-      excludeMatcher = new MatcherCollection(exclude);
+    if ('include' in options) {
```
Comment (stefanpenner) [inline index.ts:39]: test

File: index.ts [hunk 2]
```diff
@@ -28,55 +29,47 @@ namespace fixturify {
...
-      const entry = entries[i];
-      const relativePath = path.join(relativeRoot, entry);
 
-      if (includeMatcher && !includeMatcher.match(relativePath)) {
-        continue;
-      }
-
-      if (excludeMatcher && excludeMatcher.match(relativePath)) {
-        continue;
+    if ('exclude' in options) {
```
Comment (stefanpenner) [inline index.ts:48]: test

File: index.ts [hunk 3]
```diff
@@ -141,4 +134,37 @@ namespace fixturify {
   }
 }
 
+function addFile(obj: fixturify.DirJSON, path: string, content: string) {
+  const segments = path.split('/');
+  const file = segments.pop();
+
+  if (typeof file !== 'string') {
+    throw new Error('OMG');
```
Comment (stefanpenner) [inline index.ts]: better error message

File: index.ts [hunk 4]
```diff
@@ -141,4 +134,37 @@ namespace fixturify {
...
+      break;
+    }
+    const entry = obj[segment];
+    if (entry === undefined) {
+      obj = obj[segment] = {};
+    } else {
+      if (typeof entry === 'object' && entry !== null) {
+        obj = entry;
+      } else {
+        throw new Error('OMG');
```
Comment (stefanpenner) [inline index.ts]: better error message

**Comment by stefanpenner** [comment]
released as v2.1.0 🎉
